### ISSUE TITLE
Different names found in json and downloaded dataset

### ISSUE THREAD

**Issue by waychin-weiqin** [sutdcv/Animal-Kingdom#1]
Hi, 

I downloaded the pose estimation dataset and the labels (JSON format). However, the image (or video) name provided in the JSON file is not included in the downloaded dataset. May I know what the image name in the JSON file is referring to? 

For instance, in one of the JSON files, the first entry shows 'image': 'AAJYPNPL/AAJYPNPL_f000011.jpg', but the downloaded dataset only contains video files. Also, the file AAJYPNPL is not found in the downloaded dataset either. 

I look forward to your reply.

**Comment by okiane** [comment]
Hi @waychin-weiqin, thank you for your interest in our dataset! :)

The image name (AAJYPNPL/AAJYPNPL_f000011.jpg) provided in the JSON file refers to the images ($image_name/$image_sequence) untarred from _pose_estimation/dataset.tar.gz_. 

Do note that the tarred dataset file name (i.e., _dataset.tar.gz_) for all tasks (e.g., action recognition) are the same, hence there is a possibility that the wrong _dataset.tar.gz_ might have been untarred.

Also, may I know the source of your download (Google Drive or Baidu)? For Baidu, the large files are split into multiple sub-files due to the limitation of file size upload. Hence, you may need to combine them before untarring. 

Do let me know if you are able to resolve this issue.

**Comment by okiane** [comment]
> Hi,
> 
> I downloaded the pose estimation dataset and the labels (JSON format). However, the image (or video) name provided in the JSON file is not included in the downloaded dataset. May I know what the image name in the JSON file is referring to?
> 
> For instance, in one of the JSON files, the first entry shows 'image': 'AAJYPNPL/AAJYPNPL_f000011.jpg', but the downloaded dataset only contains video files. Also, the file AAJYPNPL is not found in the downloaded dataset either.
> 
> I look forward to your reply.

Hi @waychin-weiqin, thank you for your interest in our dataset! :)

The image name (AAJYPNPL/AAJYPNPL_f000011.jpg) provided in the JSON file refers to the images ($image_name/$image_sequence) untarred from pose_estimation/dataset.tar.gz.

Do note that the tarred dataset file name (i.e., dataset.tar.gz) for all tasks (e.g., action recognition) are the same, hence there is a possibility that the wrong dataset.tar.gz might have been untarred.

Also, may I know the source of your download (Google Drive or Baidu)? For Baidu, the large files are split into multiple sub-files due to the limitation of file size upload. Hence, you may need to combine them before untarring.

Do let me know if you are able to resolve this issue.

**Comment by okiane** [comment]
> Hi,
> 
> I downloaded the pose estimation dataset and the labels (JSON format). However, the image (or video) name provided in the JSON file is not included in the downloaded dataset. May I know what the image name in the JSON file is referring to?
> 
> For instance, in one of the JSON files, the first entry shows 'image': 'AAJYPNPL/AAJYPNPL_f000011.jpg', but the downloaded dataset only contains video files. Also, the file AAJYPNPL is not found in the downloaded dataset either.
> 
> I look forward to your reply.

Hi @waychin-weiqin, thank you for your interest in our dataset! :)

The image name (AAJYPNPL/AAJYPNPL_f000011.jpg) provided in the JSON file refers to the images ($image_name/$image_sequence) untarred from pose_estimation/dataset.tar.gz.

Do note that the tarred dataset file name (i.e., dataset.tar.gz) for all tasks (e.g., action recognition) are the same, hence there is a possibility that the wrong dataset.tar.gz might have been untarred.

Also, may I know the source of your download (Google Drive or Baidu)? For Baidu, the large files are split into multiple sub-files due to the limitation of file size upload. Hence, you may need to combine them before untarring.

Do let me know if you are able to resolve this issue.
